server:
  port: 8000

solon.app:
  name: demoapp
  group: demo

solon.hotplug:
  add1: "/Users/gepeng/CodeBase/Java/solon-pkg/solon-examples/1.Solon/demo1011-hotplug_plugin1/target/demo1011-hotplug_plugin1.jar"